### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by akadata** [plvisiondevs/open_vmonitor#1]
Hi, 

I downloaded from git and followed the instructions, however I get an error when logging in that I can not connect to server

**Comment by plvisiondevs** [comment]
Hi
could you please provide some additional information?

thanks,
Ihor

**Comment by vjayaramrh** [comment]
@plvisiondevs I ran into the same issue, where can I look for logs to troubleshoot
![Screen Shot 2020-09-16 at 1 09 23 PM](https://user-images.githubusercontent.com/62150532/93375507-df297e80-f81d-11ea-8b93-db25c2280949.png)

**Comment by frozen-eye** [comment]
Please look into the developers tools console (F12) in a browser at first.
If the issue is in open_vmonitor backend - look into the console where npm start been executed (attach to a container)
For the debug messages use DEBUG=*
